[2025/05/03 06:18:00] Executing command: file_deleter -d 3
2025-05-03 06:18:01.1031  Starting
GOT STOP SIGNAL
2025-05-03 08:08:56.1495  Quitting due to SIGHUP
[2025/05/03 08:08:56] Executing command: file_deleter -d 3
2025-05-03 08:08:57.0028  Starting
Traceback (most recent call last):
  File "bin/start", line 794, in <module>
    apply(command)
  File "bin/start", line 560, in command_enable_start
    found_any = run_daemons()
  File "bin/start", line 472, in run_daemons
    run_daemon(task)
  File "bin/start", line 457, in run_daemon
    write_pid_file(get_daemon_pid_name(task))
  File "bin/start", line 300, in write_pid_file
    print >>open(pidfile,'w'), os.getpid()
IOError: [Errno 13] Permission denied: u'/home/boincadm/project/pid_hello/file_deleter.pid'
[2025/05/03 08:14:39] Executing command: file_deleter -d 3
2025-05-03 08:14:39.7476  Starting
GOT STOP SIGNAL
2025-05-03 08:16:25.6169  Quitting due to SIGHUP
[2025/05/03 08:16:29] Executing command: file_deleter -d 3
2025-05-03 08:16:29.3980  Starting
GOT STOP SIGNAL
2025-05-03 08:23:06.3417  Quitting due to SIGHUP
[2025/05/03 08:23:06] Executing command: file_deleter -d 3
2025-05-03 08:23:07.1813  Starting
GOT STOP SIGNAL
2025-05-03 08:38:30.3296  Quitting due to SIGHUP
[2025/05/03 08:38:30] Executing command: file_deleter -d 3
2025-05-03 08:38:31.1818  Starting
GOT STOP SIGNAL
2025-05-03 08:39:24.6078  Quitting due to SIGHUP
[2025/05/03 08:39:25] Executing command: file_deleter -d 3
2025-05-03 08:39:25.4496  Starting
GOT STOP SIGNAL
2025-05-03 08:39:42.9082  Quitting due to SIGHUP
[2025/05/03 08:39:43] Executing command: file_deleter -d 3
2025-05-03 08:39:43.7637  Starting
